"""CuratorReport data model.

Ref: SPEC v2.0 §2.3, SPEC_V02 §2.4
"""

from __future__ import annotations

import uuid
from datetime import datetime

from pydantic import BaseModel, Field

from memory_palace.engine.health import MemoryHealthScore


class CuratorReport(BaseModel):
    """Report generated by the Memory Curator after a curation run.

    Ref: SPEC v2.0 §2.3
    """

    model_config = {"arbitrary_types_allowed": True}

    run_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    triggered_at: datetime
    trigger_reason: str  # "session_count" | "timer" | "manual"

    facts_extracted: int = 0
    memories_created: int = 0
    memories_updated: int = 0
    memories_merged: int = 0
    memories_pruned: int = 0
    reflections_generated: int = 0  # [v0.2]

    duration_seconds: float = 0
    tokens_consumed: int = 0
    errors: list[str] = []

    health_freshness: float = 0.0  # [0,1]
    health_efficiency: float = 0.0  # [0,1]

    # v0.2: full 5-dimension health score (optional — set by CuratorGraph)
    health: MemoryHealthScore | None = None
